### PR TITLE
Get rid of _'window.webkitStorageInfo' is deprecated_ warning

### LINKED ISSUE #56: 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead
**I'm submitting a bug report**

* **Library Version:**
1.0.3

**Please tell us about your environment:**
* **Operating System:**
Linux F27

* **Node Version:**
8.9.4

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
webpack 4

* **Browser:**
Chrome Version 65.0.3325.146 (Official Build) (64-bit)

* **Language:**
TypeScript 2.7.2

**Current behavior:**

I just started using viewports in a few of my routing behaviours. The Chrome devtools console is giving me this warning:

```
aurelia-metadata.js?c04d:64 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
(anonymous) @ aurelia-metadata.js?c04d:64
(anonymous) @ aurelia-loader-webpack.js?b873:144
WebpackLoader.__WEBPACK_IMPORTED_MODULE_2_aurelia_pal__.PLATFORM.eachModule @ aurelia-loader-webpack.js?b873:141
get @ aurelia-metadata.js?c04d:61
getViewStrategy @ aurelia-templating.js?f83c:690
process @ router-view.js?e967:113
_loop @ aurelia-router.js?ec12:291
_commitChanges @ aurelia-router.js?ec12:305
(anonymous) @ aurelia-router.js?ec12:293
Promise.then (async)
_loop @ aurelia-router.js?ec12:291
_commitChanges @ aurelia-router.js?ec12:305
(anonymous) @ aurelia-router.js?ec12:293
Promise.then (async)
_loop @ aurelia-router.js?ec12:291
_commitChanges @ aurelia-router.js?ec12:305
run @ aurelia-router.js?ec12:143
next @ aurelia-router.js?ec12:112
iterate @ aurelia-router.js?ec12:1302
inspect @ aurelia-router.js?ec12:1279
(anonymous) @ aurelia-router.js?ec12:1295
```

It is specifically complaining about [this line](https://github.com/aurelia/metadata/blob/1f4c3e4ea4540b3842ed0e9d987e20a42f02eff4/dist/commonjs/aurelia-metadata.js#L76)

Console

**Expected/desired behavior:**

* **What is the expected behavior?**

The library should be updated to not use the deprecated functionality.

* **What is the motivation / use case for changing the behavior?**

Remove console deprecation warnings

### PR DESCRIPTION
**Pull request by josundt**
Fixes #56

### CODE REVIEW

File: src/origin.js [hunk 1]
```diff
@@ -37,7 +37,9 @@ export class Origin {
     if (origin === undefined) {
       PLATFORM.eachModule((key, value) => {
         if (typeof value === 'object') {
+          var isBrowserWindow = typeof window !== 'undefined' && value === window;
```
Comment (avrahamcool) [inline src/origin.js:40]: why use `var` in this context? `const` is more appropriate.
also: checking if `value === window` should suffice.

Comment (bigopon) [reply src/origin.js:40]: well agree about `var`. Though it seems in v1, we always use `let`, so maybe change it to that?
About the check, I think we should have `typeof`, as we want to make sure if this module is used in node (jest test for example), it won't break others.

Comment (avrahamcool) [reply src/origin.js:40]: @bigopon regarding the typeof. but you have a strict equality between `value` and `window`, and one line before that you already checked that `typeof` value is `object`. so even without knowing anything about platform etc.. this is an obvious redundancy.

Comment (bigopon) [reply src/origin.js:40]: Right, missed that line. Thanks!

Comment (josundt) [reply src/origin.js:40]: Even if we have already checked that `typeof value === 'object'`, in a node environment the condition `value === window` will throw when `window` is not defined. The `typeof window !== 'undefined'` is there to prevent this as pointed out by @bigopon.
I can correct the `var` to `let`, OK?

Comment (avrahamcool) [reply src/origin.js:40]: you are right. my bad.
doesn't aurelia have the PLATFORM abstraction exactly for this type of gotchas?

Comment (josundt) [reply src/origin.js]: @bigopon @avrahamcool I have now corrected the `var` to `let` (not `const` since this was said to be a convention in v1).
Forgot that the I was editing pre-transpilation code for a second :-)

Comment (bigopon) [reply src/origin.js]: Yeah right... oh well at least we botg missed it. Feel less bad 😅 

Thanks @josundt

**Comment by josundt** [comment]
Anything else or will you approve the PR?
If approved; will you trigger a new release as well?

**Comment by avrahamcool** [comment]
> Anything else or will you approve the PR?
> If approved; will you trigger a new release as well?

I think this is safe to deploy.

**Comment by bigopon** [comment]
Lgtm, though we will need to ping @EisenbergEffect for the merge and release.

**Review by avrahamcool — APPROVED** [review]

**Comment by josundt** [comment]
@bigopon Any chance that this PR will be approved soon (followed by a package release)?

**Comment by josundt** [comment]
@EisenbergEffect Thanks for accepting and merging 🙂 
When can a release to be expected?

**Comment by EisenbergEffect** [comment]
Should be soon. I had some issues building recently which has caused the delay.

**Comment by EisenbergEffect** [comment]
Hey folks, I apologize for the delay. We're still having some issues with the build. @bigopon is exploring what might be going on and we are looking to some alternative ways to get this out.

**Comment by elitastic** [comment]
Newest **npm** package 1.0.7 seems to be different from 1.0.7 release here on github (related changes from this issue are missing in npm package), is this still due to build troubles?

**Comment by josundt** [comment]
@bigopon Looks like @elitastic is right. Inside the package, the `src` folder contains my PR changes, but the `dist` folder does not include the changes. Looks like the build did not update the dist folder....

**Comment by bigopon** [comment]
Thanks @elitastic @josundt 
I'll probably have to update few deps to make this work, as it's a problem with different version of Node Rob's running on. Will update

**Comment by josundt** [comment]
@bigopon well?

**Comment by bigopon** [comment]
From our merged pull request here https://github.com/aurelia/metadata/pull/66/files it's definitely updated, just there's an issue those updates are overridden. It seems @fkleuver will have to take over the release of this, or @EisenbergEffect will need to use an nvm to run the release script. Or we will have to update our gulp & stuff to make sure it works on Node 12. Let me chat with the team how we want to do it, because we want to do it for all of the repos as well, possibly.

**Comment by josundt** [comment]
@bigopon Looks like this will not be fixed?

**Comment by bigopon** [comment]
Yes it will be.

**Comment by bigopon** [comment]
I have created a PR to upgrade the build process, so @EisenbergEffect can release smoothly again. The PR is here #69

**Comment by josundt** [comment]
Looks like accociated PR #69 😏 was merged.
Can I expect a new version released soon?
